-- Migration 001: Initial Schema
-- Enable Vector Extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Companions (The AI Entity)
CREATE TABLE IF NOT EXISTS public."Companions" (
    companion_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    name VARCHAR(50) NOT NULL,
    relationship_type VARCHAR(50),
    tone_style VARCHAR(50),
    summary TEXT DEFAULT '',
    active_traits JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Chat_Logs (Raw History)
CREATE TABLE IF NOT EXISTS public."Chat_Logs" (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companion_id UUID REFERENCES public."Companions"(companion_id) ON DELETE CASCADE,
    sender VARCHAR(10) CHECK (sender IN ('USER', 'AI')),
    message TEXT NOT NULL,
    embedding vector(1536),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Daily_Emotions (Prism Log)
CREATE TABLE IF NOT EXISTS public."Daily_Emotions" (
    date DATE NOT NULL,
    companion_id UUID REFERENCES public."Companions"(companion_id) ON DELETE CASCADE,
    primary_emotion VARCHAR(50),
    color_hex VARCHAR(7),
    summary_text TEXT,
    key_quote TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (date, companion_id)
);

-- 4. User_Inventory (Digital Assets)
CREATE TABLE IF NOT EXISTS public."User_Inventory" (
    item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    item_type VARCHAR(50),
    image_url TEXT,
    metadata JSONB,
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Subscriptions
CREATE TABLE IF NOT EXISTS public."Subscriptions" (
    user_id UUID PRIMARY KEY,
    plan_type VARCHAR(20) DEFAULT 'FREE',
    is_active BOOLEAN DEFAULT TRUE
);

-- Index for vector similarity search on Chat_Logs
CREATE INDEX IF NOT EXISTS idx_chat_logs_embedding
ON public."Chat_Logs"
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);
